name: Build and Deploy

on:
  push:
    branches:
      - main  # replace with your default branch if not "main"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.5.3'  # replace with your Flutter version

    - name: Build and Deploy
      run: |
        export API_KEY=${{ secrets.API_KEY }}
        flutter pub get
        flutter test
        flutter build web --release --dart-define=API_KEY=$API_KEY

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: /
